from __future__ import annotations

"""
ENVI 标准格式写出工具。

提供 write_envi(output_stem, cube, interleave="bsq", dtype=None)：
- 根据给定的三维数组 cube（形状 (H, W, B)）写出 ENVI 头文件 (.hdr)
  和二进制数据文件 (.dat)。
- 仅依赖 numpy 与标准库，不强制依赖 spectral。

注意：
- 本工具假设字节序为小端（byte order = 0）；
- 数据类型需能映射到 ENVI data type 编码。
"""

from typing import Optional, Tuple

import os
import numpy as np


# ENVI data type 映射表（与 envi_reader 中使用的约定保持一致）
_DTYPE_TO_ENVI: dict[str, int] = {
    "uint8": 1,
    "int16": 2,
    "int32": 3,
    "float32": 4,
    "float64": 5,
    "complex64": 6,
    "complex128": 9,
    "uint16": 12,
    "uint32": 13,
    "int64": 14,
    "uint64": 15,
}


def _normalize_dtype(dtype: np.dtype) -> Tuple[np.dtype, int]:
    """
    将 numpy dtype 归一化为 ENVI 支持的 dtype + data type 编码。

    返回 (dtype_without_endian, envi_code)。
    """
    dt = np.dtype(dtype)
    # 去除字节序标记，只保留类型本身
    base_str = dt.newbyteorder("=").name  # 例如 'float32'
    if base_str not in _DTYPE_TO_ENVI:
        raise ValueError(f"无法将数据类型映射到 ENVI data type: {dtype!r}")
    code = _DTYPE_TO_ENVI[base_str]
    return np.dtype(base_str), code


def write_envi(
    output_stem: str,
    cube: np.ndarray,
    interleave: str = "bsq",
    dtype: Optional[np.dtype] = None,
) -> Tuple[str, str]:
    """
    将三维高光谱数据写出为 ENVI 标准格式（.hdr + .dat）。

    参数：
        output_stem: 输出文件主名（不含扩展名），例如 "D:/data/out/envi_cube"
                     将生成 "envi_cube.hdr" 与 "envi_cube.dat"。
        cube: 三维 numpy 数组，形状为 (lines, samples, bands) = (H, W, B)
        interleave: 数据排列方式，'bsq' / 'bil' / 'bip'
        dtype: 可选，指定输出 dtype；若为 None，则使用 cube.dtype

    返回：
        (hdr_path, dat_path)
    """
    arr = np.asarray(cube)
    if arr.ndim != 3:
        raise ValueError(f"ENVI 写出仅支持三维数组，当前维度为 {arr.ndim}")

    lines, samples, bands = arr.shape

    if dtype is None:
        dtype = arr.dtype
    dtype_norm, data_type_code = _normalize_dtype(dtype)

    interleave = interleave.lower()
    if interleave not in {"bsq", "bil", "bip"}:
        raise ValueError(f"不支持的 interleave：{interleave!r}（期望 bsq/bil/bip）")

    # 输出路径
    hdr_path = output_stem + ".hdr"
    dat_path = output_stem + ".dat"

    # 按 interleave 组织数据并写出二进制
    if interleave == "bsq":
        # (H, W, B) -> (B, H, W) 然后展平
        out_arr = np.transpose(arr, (2, 0, 1)).astype(dtype_norm, copy=False)
    elif interleave == "bil":
        # (H, W, B) -> (H, B, W)
        out_arr = np.transpose(arr, (0, 2, 1)).astype(dtype_norm, copy=False)
    else:  # bip
        # (H, W, B) 保持不变
        out_arr = arr.astype(dtype_norm, copy=False)

    # 以小端方式写出
    out_arr = out_arr.astype(dtype_norm.newbyteorder("<"), copy=False)
    os.makedirs(os.path.dirname(os.path.abspath(dat_path)), exist_ok=True)
    with open(dat_path, "wb") as f:
        out_arr.tofile(f)

    # 写出 ENVI 头文件
    header_lines = [
        "ENVI",
        "description = {Generated by envi_writer}",
        f"samples = {samples}",
        f"lines   = {lines}",
        f"bands   = {bands}",
        f"data type = {data_type_code}",
        f"interleave = {interleave}",
        "byte order = 0",  # 小端
    ]

    with open(hdr_path, "w", encoding="utf-8") as f:
        f.write("\n".join(header_lines) + "\n")

    return hdr_path, dat_path

